# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20181019_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_receiver',
        ),
    ]
